// File generated by SewaBot setup — do not edit manually.
// Firebase project: sewabot-e836a

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQmxvxil6L59EWR_THwAvJJXQdelruj68',
    appId: '1:339233439687:web:60e37d09e919285e00a3e2',
    messagingSenderId: '339233439687',
    projectId: 'sewabot-e836a',
    authDomain: 'sewabot-e836a.firebaseapp.com',
    storageBucket: 'sewabot-e836a.firebasestorage.app',
    measurementId: 'G-H3D48E5TDV',
  );

  // Android / iOS placeholders — update with google-services.json values when building APK
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQmxvxil6L59EWR_THwAvJJXQdelruj68',
    appId: '1:339233439687:web:60e37d09e919285e00a3e2',
    messagingSenderId: '339233439687',
    projectId: 'sewabot-e836a',
    storageBucket: 'sewabot-e836a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQmxvxil6L59EWR_THwAvJJXQdelruj68',
    appId: '1:339233439687:web:60e37d09e919285e00a3e2',
    messagingSenderId: '339233439687',
    projectId: 'sewabot-e836a',
    storageBucket: 'sewabot-e836a.firebasestorage.app',
  );
}
